;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				emmet-expand-line
				indent-for-tab-command
				sgml-close-tag
				sgml-maybe-name-self
				sgml-slash
				))

(setq mc/cmds-to-run-once
      '(
				ido-find-file
				kill-region
				))
