;; campainha-light-theme.el --- Theme

;; Copyright (C) 2016 , Vinícius Sales

;; Author: Vinícius Sales
;; Version: 0.1
;; Package-Requires: ((emacs "24"))
;; Created with ThemeCreator, https://github.com/mswift42/themecreator.


;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.

;; This file is not part of Emacs.

;;; Commentary:

;;; Code:

(deftheme campainha-light)
(let ((class '((class color) (min-colors 89)))
      ;; Campainha Collor Palette - based on Tailwind CSS Grey palette
      (color-white "#FFFFFF")
      (color-lightest "#F8FAFC")
      (color-lighter "#F1F5F8")
      (color-light "#DAE1E7")
      (color-base "#B8C2CC")
      (color-dark "#8795A1")
      (color-darker "#606F7B")
      (color-darkest "#3D4852")
      (color-black "#22292F")

      (color-grey-dark    "#474747")
      (color-grey         "#737373")
      (color-grey-light   "#CCCCCC")
      (color-grey-lighter "#EBEBEB")
      (color-purple-dark  "#510755")
      (color-purple       "#750A7B")
      (color-yellow-dark  "#ECB913")
      (color-yellow       "#EFC334")
      (color-sand-dark    "#EAE7CD")
      (color-sand         "#F9F8F0")
      (color-cyan         "#3ECBDA")
      (color-pink         "#E5248B")
      (color-red          "#E52457")

      ;; Genéricos
      (background "#F9F8F0")
      (foreground "#474747")

      ;; Syntax Highlighting
      (builtin "#474747")
      (keyword "#474747")
      (const   "#474747")
      (comment "#CCCCCC")
      (doc     "#B3B3B3")
      (func    "#474747")
      (str     "#737373")
      (type    "#474747")
      (var     "#474747"))
  (custom-theme-set-faces
   'campainha-light
   `(default ((,class (:background ,background :foreground ,foreground))))
   `(font-lock-builtin-face ((,class (:foreground ,builtin))))
   `(font-lock-comment-face ((,class (:foreground ,comment))))
   `(font-lock-constant-face ((,class (:foreground ,const))))
   `(font-lock-doc-face ((,class (:foreground ,doc))))
   `(font-lock-function-name-face ((,class (:foreground ,func ))))
   `(font-lock-keyword-face ((,class (:foreground ,keyword))))
   `(font-lock-negation-char-face ((,class (:foreground ,const))))
   `(font-lock-reference-face ((,class (:foreground ,const))))
   `(font-lock-string-face ((,class (:foreground ,str))))
   `(font-lock-type-face ((,class (:foreground ,type ))))
   `(font-lock-variable-name-face ((,class (:foreground ,var))))
   `(font-lock-warning-face ((,class (:foreground ,color-red :background ,color-grey-dark))))
   `(region ((,class (:background ,color-yellow))))
   `(highlight ((,class (:foreground ,color-grey :background ,color-grey-dark))))
   `(hl-line ((,class (:background ,color-sand-dark))))
   `(fringe ((,class (:background ,color-sand-dark))))
   `(cursor ((,class (:background ,color-purple :foreground ,foreground))))
   `(show-paren-match-face ((,class (:background ,color-red))))
   `(isearch ((,class (:bold t :foreground ,color-black :background ,color-light))))
   `(mode-line ((,class (:box nil :underline nil :overline nil :background ,color-purple-dark :foreground ,color-white))))
   `(powerline-active1 ((,class (:background ,color-purple :foreground ,color-white))))
   `(powerline-active2 ((,class (:background ,color-pink :foreground ,color-white))))
   `(mode-line-inactive ((,class (:box nil :underline nil :overline nil :background ,color-grey :foreground ,color-grey-dark))))
   `(powerline-inactive1 ((,class (:background ,color-grey-light :foreground ,color-grey))))
   `(powerline-inactive2 ((,class (:background ,color-grey-lighter :foreground ,color-grey-light))))
   ;; `(mode-line-buffer-id ((,class (:bold t :foreground ,func :background nil))))
   ;; `(mode-line-highlight ((,class (:foreground ,keyword :box nil :weight bold))))
   ;; `(mode-line-emphasis ((,class (:foreground ,foreground))))
   `(vertical-border ((,class (:foreground ,color-grey))))
   `(minibuffer-prompt ((,class (:bold t :foreground ,keyword))))
   `(default-italic ((,class (:italic t))))
   `(link ((,class (:foreground ,const :underline t))))

   ;; Elixir
   `(elixir-atom-face ((,class (:foreground ,foreground))))
   `(elixir-attribute-face ((,class (:foreground ,foreground))))

   ;; Flycheck
   `(flycheck-error ((,class (:background ,color-red :foreground ,color-white))))
   `(flycheck-warning ((,class (:background ,color-yellow-dark :foreground ,color-white))))
   `(flycheck-info ((,class (:background ,color-cyan :foreground ,color-white))))
   `(flycheck-fringe-error ((,class (:background ,color-red :foreground ,color-white))))
   `(flycheck-fringe-warning ((,class (:background ,color-yellow-dark :foreground ,color-white))))
   `(flycheck-fringe-info ((,class (:background ,color-cyan :foreground ,color-white))))
   `(flycheck-error-list-error ((,class (:foreground ,color-red))))
   `(flycheck-error-list-warning ((,class (:foreground ,color-yellow))))
   `(flycheck-error-list-info ((,class (:foreground ,color-cyan))))
   `(flycheck-error-list-checker-name ((,class (:foreground ,str))))

   ;; Org-mode
   `(org-code ((,class (:foreground ,foreground))))
   `(org-hide ((,class (:foreground ,background))))
   `(org-level-1 ((,class (:bold nil :foreground ,foreground :height 1.3))))
   `(org-level-2 ((,class (:bold nil :foreground ,foreground :height 1.2))))
   `(org-level-3 ((,class (:bold nil :foreground ,foreground :height 1.1))))
   `(org-level-4 ((,class (:bold nil :foreground ,foreground))))
   `(org-date ((,class (:underline t :foreground ,var) )))
   `(org-footnote  ((,class (:underline t :foreground ,color-grey))))
   `(org-link ((,class (:underline t :foreground ,type ))))
   `(org-special-keyword ((,class (:foreground ,func))))
   `(org-block ((,class (:foreground ,color-grey))))
   `(org-quote ((,class (:inherit org-block :slant italic))))
   `(org-verse ((,class (:inherit org-block :slant italic))))
   `(org-todo ((,class (:box nil :foreground ,color-red :bold t))))
   `(org-done ((,class (:box nil :foreground ,color-cyan :bold t))))
   `(org-warning ((,class (:underline t :foreground ,color-red))))
   `(org-agenda-structure ((,class (:weight bold :foreground ,color-grey :box (:color ,color-grey) :background ,color-grey-dark))))
   `(org-agenda-date ((,class (:foreground ,var :height 1.1 ))))
   `(org-agenda-date-weekend ((,class (:weight normal :foreground ,color-grey))))
   `(org-agenda-date-today ((,class (:weight bold :foreground ,keyword :height 1.4))))
   `(org-agenda-done ((,class (:foreground ,color-grey-dark))))
   `(org-scheduled ((,class (:foreground ,type))))
   `(org-scheduled-today ((,class (:foreground ,func :weight bold :height 1.2))))
   `(org-ellipsis ((,class (:foreground ,builtin))))
   `(org-verbatim ((,class (:foreground ,color-grey))))
   `(org-document-info-keyword ((,class (:foreground ,func))))
   `(org-sexp-date ((,class (:foreground ,color-grey))))

   `(font-latex-bold-face ((,class (:foreground ,type))))
   `(font-latex-italic-face ((,class (:foreground ,var :italic t))))
   `(font-latex-string-face ((,class (:foreground ,str))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,const))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,var))))
   `(ido-subdir ((,class (:foreground ,color-dark))))
   `(ido-only-match ((,class (:foreground ,foreground :bold t))))
   `(ido-first-match ((,class (:foreground ,keyword :bold t))))
   `(gnus-header-content ((,class (:foreground ,keyword))))
   `(gnus-header-from ((,class (:foreground ,var))))
   `(gnus-header-name ((,class (:foreground ,type))))
   `(gnus-header-subject ((,class (:foreground ,func :bold t))))
   `(mu4e-view-url-number-face ((,class (:foreground ,type))))
   `(mu4e-cited-1-face ((,class (:foreground ,color-grey))))
   `(mu4e-cited-7-face ((,class (:foreground ,color-grey))))
   `(mu4e-header-marks-face ((,class (:foreground ,type))))
   `(ffap ((,class (:foreground ,color-grey))))
   `(js2-external-variable ((,class (:foreground ,type  ))))
   `(js2-function-param ((,class (:foreground ,const))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,str))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,str))))
   `(js2-jsdoc-tag ((,class (:foreground ,str))))
   `(js2-jsdoc-type ((,class (:foreground ,str))))
   `(js2-jsdoc-value ((,class (:foreground ,str))))
   `(js2-private-function-call ((,class (:foreground ,const))))
   `(js2-private-member ((,class (:foreground ,color-grey))))
   `(js3-error-face ((,class (:underline ,color-red))))
   `(js3-external-variable-face ((,class (:foreground ,var))))
   `(js3-function-param-face ((,class (:foreground ,color-grey))))
   `(js3-instance-member-face ((,class (:foreground ,const))))
   `(js3-jsdoc-tag-face ((,class (:foreground ,keyword))))
   `(js3-warning-face ((,class (:underline ,keyword))))
   `(warning ((,class (:foreground ,color-red)))) 
   `(ac-completion-face ((,class (:underline t :foreground ,keyword))))
   `(info-quoted-name ((,class (:foreground ,builtin))))
   `(info-string ((,class (:foreground ,str))))
   `(icompletep-determined ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-current-face ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-default-face ((,class :foreground ,color-grey)))
   `(undo-tree-visualizer-unmodified-face ((,class :foreground ,var)))
   `(undo-tree-visualizer-register-face ((,class :foreground ,type)))
   `(slime-repl-inputed-output-face ((,class (:foreground ,type))))
   `(trailing-whitespace ((,class :foreground nil :background ,color-red)))
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,foreground)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,type)))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,var)))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,const)))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,keyword)))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,foreground)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,type)))
   `(rainbow-delimiters-depth-8-face ((,class :foreground ,var)))

   ;; Magit
   ;; magit-diff-highlight-hunk-region-using-face
   `(magit-branch ((,class (:foreground ,const :weight bold))))
   `(magit-diff-context ((,class (:background ,color-lighter :foreground ,comment))))
   `(magit-diff-context-highlight ((,class (:background ,color-lighter :foreground ,foreground))))
   `(magit-diff-hunk-heading ((,class (:background ,color-light :foreground ,comment))))
   `(magit-diff-hunk-heading-highlight ((,class (:background ,color-light, :foreground ,foreground))))
   `(magit-diff-file-header ((,class (:foreground ,color-grey :background ,color-grey-dark))))
   `(magit-diffstat-added   ((,class (:foreground ,type))))
   `(magit-diffstat-removed ((,class (:foreground ,var))))
   `(magit-hash ((,class (:foreground ,color-grey))))
   `(magit-hunk-heading           ((,class (:background ,color-base))))
   `(magit-hunk-heading-highlight ((,class (:background ,color-base, :foreground ,foreground))))
   `(magit-item-highlight ((,class :background ,color-grey-dark)))
   `(magit-log-author ((,class (:foreground ,color-grey))))
   `(magit-process-ng ((,class (:foreground ,color-red :weight bold))))
   `(magit-process-ok ((,class (:foreground ,func :weight bold))))
   `(magit-section-heading ((,class (:foreground ,keyword :weight bold))))
   `(magit-section-highlight ((,class (:background ,background :foreground ,foreground))))

   `(lazy-highlight ((,class (:foreground ,color-grey :background ,color-grey-dark))))
   `(term ((,class (:foreground ,foreground :background ,background))))
   `(term-color-black ((,class (:foreground ,color-grey-dark :background ,color-grey-dark))))
   `(term-color-blue ((,class (:foreground ,func :background ,func))))
   `(term-color-red ((,class (:foreground ,keyword :background ,color-grey-dark))))
   `(term-color-green ((,class (:foreground ,type :background ,color-grey-dark))))
   `(term-color-yellow ((,class (:foreground ,var :background ,var))))
   `(term-color-magenta ((,class (:foreground ,builtin :background ,builtin))))
   `(term-color-cyan ((,class (:foreground ,str :background ,str))))
   `(term-color-white ((,class (:foreground ,color-grey :background ,color-grey))))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,color-red)))
   `(helm-header ((,class (:foreground ,color-grey :background ,background :underline nil :box nil))))
   `(helm-source-header ((,class (:foreground ,keyword :background ,background :underline nil :weight bold))))
   `(helm-selection ((,class (:background ,color-grey-dark :underline nil))))
   `(helm-selection-line ((,class (:background ,color-grey-dark))))
   `(helm-visible-mark ((,class (:foreground ,background :background ,color-grey-dark))))
   `(helm-candidate-number ((,class (:foreground ,background :background ,foreground))))
   `(helm-separator ((,class (:foreground ,type :background ,background))))
   `(helm-time-zone-current ((,class (:foreground ,builtin :background ,background))))
   `(helm-time-zone-home ((,class (:foreground ,type :background ,background))))
   `(helm-buffer-not-saved ((,class (:foreground ,type :background ,background))))
   `(helm-buffer-process ((,class (:foreground ,builtin :background ,background))))
   `(helm-buffer-saved-out ((,class (:foreground ,foreground :background ,background))))
   `(helm-buffer-size ((,class (:foreground ,foreground :background ,background))))
   `(helm-ff-directory ((,class (:foreground ,func :background ,background :weight bold))))
   `(helm-ff-file ((,class (:foreground ,foreground :background ,background :weight normal))))
   `(helm-ff-executable ((,class (:foreground ,var :background ,background :weight normal))))
   `(helm-ff-invalid-symlink ((,class (:foreground ,color-yellow :background ,background :weight bold))))
   `(helm-ff-symlink ((,class (:foreground ,keyword :background ,background :weight bold))))
   `(helm-ff-prefix ((,class (:foreground ,background :background ,keyword :weight normal))))
   `(helm-grep-cmd-line ((,class (:foreground ,foreground :background ,background))))
   `(helm-grep-file ((,class (:foreground ,foreground :background ,background))))
   `(helm-grep-finish ((,class (:foreground ,color-grey :background ,background))))
   `(helm-grep-lineno ((,class (:foreground ,foreground :background ,background))))
   `(helm-grep-match ((,class (:foreground nil :background nil :inherit helm-match))))
   `(helm-grep-running ((,class (:foreground ,func :background ,background))))
   `(helm-moccur-buffer ((,class (:foreground ,func :background ,background))))
   `(helm-source-go-package-godoc-description ((,class (:foreground ,str))))
   `(helm-bookmark-w3m ((,class (:foreground ,type))))
   `(company-echo-common ((,class (:foreground ,background :background ,foreground))))
   `(company-preview ((,class (:background ,background :foreground ,foreground))))
   `(company-preview-common ((,class (:foreground ,color-grey-dark :foreground ,foreground))))
   `(company-preview-search ((,class (:foreground ,type :background ,background))))
   `(company-scrollbar-bg ((,class (:background ,color-yellow-dark))))
   `(company-scrollbar-fg ((,class (:background ,color-sand-dark))))
   `(company-tooltip ((,class (:foreground ,color-grey :background ,color-yellow))))
   `(company-tooltop-annotation ((,class (:foreground ,const))))
   `(company-tooltip-common ((,class (:foreground ,foreground))))
   `(company-tooltip-common-selection ((,class (:foreground ,foreground))))
   `(company-tooltip-mouse ((,class (:inherit highlight))))
   `(company-tooltip-selection ((,class (:background ,color-yellow-dark :foreground ,color-grey :bold t))))
   `(company-template-field ((,class (:inherit region))))
   `(web-mode-attr-tag-custom-face ((,class (:color-darker :bold nil))))
   `(web-mode-block-attr-name-face ((,class (:foreground ,foreground))))
   `(web-mode-block-attr-value-face ((,class (:foreground ,foreground))))
   `(web-mode-block-comment-face ((,class (:foreground ,foreground))))
   `(web-mode-block-control-face ((,class (:foreground ,foreground))))
   `(web-mode-block-delimiter-face ((,class (:foreground ,foreground))))
   `(web-mode-block-face ((,class (:foreground ,foreground))))
   `(web-mode-block-string-face ((,class (:foreground ,foreground))))
   `(web-mode-builtin-face ((,class (:foreground ,foreground))))
   `(web-mode-comment-face ((,class (:foreground ,comment))))
   `(web-mode-constant-face ((,class (:foreground ,foreground))))
   `(web-mode-doctype-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-filter-face ((,class (:foreground ,foreground))))
   `(web-mode-function-call-face ((,class (:foreground ,foreground))))
   `(web-mode-function-name-face ((,class (:foreground ,foreground))))
   `(web-mode-html-attr-equal-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-html-attr-value-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-html-tag-bracket-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-html-tag-custom-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-html-tag-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-html-tag-namespaced-face ((,class (:foreground ,color-darker :bold nil))))
   `(web-mode-keyword-face ((,class (:foreground ,foreground))))
   `(web-mode-preprocessor-face ((,class (:foreground ,foreground))))
   `(web-mode-string-face ((,class (:foreground ,foreground))))
   `(web-mode-symbol-face ((,class (:foreground ,foreground))))
   `(web-mode-type-face ((,class (:foreground ,foreground))))
   `(web-mode-variable-name-face ((,class (:foreground ,foreground))))
   `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
   `(jde-java-font-lock-package-face ((t (:foreground ,var))))
   `(jde-java-font-lock-public-face ((t (:foreground ,keyword))))
   `(jde-java-font-lock-private-face ((t (:foreground ,keyword))))
   `(jde-java-font-lock-constant-face ((t (:foreground ,const))))
   `(jde-java-font-lock-modifier-face ((t (:foreground ,foreground))))
   `(jde-jave-font-lock-protected-face ((t (:foreground ,keyword))))
   `(jde-java-font-lock-number-face ((t (:foreground ,var))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'campainha-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; campainha-light-theme.el ends here
